@echo off
title Bootloader
echo -----------------------------------
echo Starting Kernel.....
timeout /t 2 >nul
echo Starting LogonUI.....
timeout /t 2 >nul
echo Starting Services.....
timeout /t 2 >nul
echo Please wait while we load the system.....
timeout /t 5 >nul
call fileload.bat